### ISSUE TITLE
Together we can change the world, just one random act of kindness at a time

### ISSUE THREAD

**Issue by KingBTC** [rubykube/peatio#1801]

**Comment by mod** [comment]
Hello Sir,

If you want to advertise your services, please contribute to open-source, also disclose your real name and reference.

**Comment by KingBTC** [comment]
@Thedabest spammer block & account reported ! Hey , I have seen you spamming everywhere please stop going to all issues and spamming and stop promote your fake services !

**Comment by KingBTC** [comment]
@mod mon nom est Patrick et je contribuerai plus bientôt

**Comment by vpetrusenko** [comment]
@KingBTC there is ZERO contribution from you, your  account is created 5 hours ago
![screenshot 1](https://user-images.githubusercontent.com/26842923/48196943-b8b27680-e35c-11e8-9d2b-cc3117d9da1b.png)
