### ISSUE TITLE
Can't open site

### ISSUE THREAD

**Issue by OKPayCurrency** [rubykube/peatio#2054]
I have successfully installed Peatio on my Debian VPS (DO) but I can't access peatio on my debian ip This site can’t be reached

I have done several configurations

./bin/setup

god -c lib / daemons / daemons.god

Add this to my hosts

127.0.0.1 www.myip
127.0.0.1 peatio.myip
127.0.0.1 barong.myip

Start rails server JWT_PUBLIC_KEY = $ (cat config / secrets / rsa-key.pub | base64 -w0) rails s -b0.0.0.0

What should I do? Please help

**Comment by ysv** [comment]
@OKPayCurrency Try to access server via www.myip
